function [EventType,Code,Time,Subject,Trial,Duration] = importfile_Presentation_log(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [SUBJECT,TRIAL,EVENTTYPE,CODE,TIME,TTIME,UNCERTAINTY,DURATION,UNCERTAINTY1,REQTIME,REQDUR,STIMTYPE,PAIRINDEX]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [SUBJECT,TRIAL,EVENTTYPE,CODE,TIME,TTIME,UNCERTAINTY,DURATION,UNCERTAINTY1,REQTIME,REQDUR,STIMTYPE,PAIRINDEX]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Subject,Trial,EventType,Code,Time,TTime,Uncertainty,Duration,Uncertainty1,ReqTime,ReqDur,StimType,PairIndex]
%   =
%   importfile('Run7_Standard_EPI_epilepsy_study-Neutral_faces_scenario.log',4,
%   463);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/10/26 15:20:32

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 4;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[4,5,6,7,8]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [4,5,6,7,8]);
rawCellColumns = raw(:, [1,2,3,9,10,11,12,13]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
Subject = rawCellColumns(:, 1);
Trial = rawCellColumns(:, 2);
EventType = rawCellColumns(:, 3);
Code = cell2mat(rawNumericColumns(:, 1));
Time = cell2mat(rawNumericColumns(:, 2));
TTime = cell2mat(rawNumericColumns(:, 3));
Uncertainty = cell2mat(rawNumericColumns(:, 4));
Duration = cell2mat(rawNumericColumns(:, 5));
Uncertainty1 = rawCellColumns(:, 4);
ReqTime = rawCellColumns(:, 5);
ReqDur = rawCellColumns(:, 6);
StimType = rawCellColumns(:, 7);
PairIndex = rawCellColumns(:, 8);

Time = (Time - Time(1))/10000;
Duration = Duration/10000;
